"""Add document_filename column

Revision ID: 410d124f8531
Revises: 3d5d7b42c13b
Create Date: 2024-05-23 11:16:56.622429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410d124f8531'
down_revision = '3d5d7b42c13b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('document_filename',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('document_filename',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
