"""Add document_filename column

Revision ID: 9b71db09580d
Revises: 410d124f8531
Create Date: 2024-05-23 11:23:18.316868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b71db09580d'
down_revision = '410d124f8531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('document_filename',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('doc_name')
        batch_op.drop_column('file_size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('doc_name', sa.VARCHAR(length=30), nullable=False))
        batch_op.alter_column('document_filename',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
